/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import BOs.CancelacionesBO;
import BOs.ClienteBO;
import BOs.MesaBO;
import BOs.ReservaBO;
import DAO.CancelacionDAO;
import DAO.ClienteDAO;
import DAO.MesaDAO;
import DAO.ReservaDAO;
import DAO.SucursalDAO;
import Dto.CancelacionDTO;
import Dto.ClienteDTO;
import Dto.ReservaDTO;
import Dto.SucursalDTO;
import Entidades.Reserva;
import java.awt.List;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author gaspa
 */
public class frmRestaurante extends javax.swing.JFrame {
    ReservaBO reservaBO;
    ClienteBO clienteBO;
    ReservaDAO reservaDAO;
    MesaBO mesaBO;
    MesaDAO mesaDAO;
    ClienteDAO clienteDAO;
    SucursalDAO sucursalDAO;
    CancelacionDAO cancelacionDAO;
    CancelacionesBO cancelacionesBO;
    /**
     * Creates new form frmRestaurante
     */
    public frmRestaurante() {
        initComponents();
        reservaBO = new ReservaBO();
        clienteBO = new ClienteBO();
        reservaDAO = new ReservaDAO();
        mesaBO = new MesaBO();
        mesaDAO = new MesaDAO();
        clienteDAO = new ClienteDAO();
        sucursalDAO = new SucursalDAO();
        cancelacionDAO = new CancelacionDAO();
        cancelacionesBO = new CancelacionesBO();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reservasDateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reservasLugarComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reservasCostoReservaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        reservasNumPersonasTextField = new javax.swing.JTextField();
        reservasConfirmarBtn = new javax.swing.JButton();
        reservasConfirmarBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservasTablaClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mesasTablaMesas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mesasTipoMesaComboBox = new javax.swing.JComboBox<>();
        mesasUbicacionComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        mesasCantidadTxt = new javax.swing.JTextField();
        agregarMesasBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cancelacionesTablaReservas = new javax.swing.JTable();
        cancelacionesMultaTxt = new javax.swing.JTextField();
        cancelacionesCalcularMultaBtn = new javax.swing.JButton();
        cancelacionesConfirmarBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        cancelacionesTablaCancelaciones = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        reportesDatePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        reportesDatePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        reportesTipoMesaComboBox = new javax.swing.JComboBox<>();
        reportesUbicacionComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportesjTable = new javax.swing.JTable();
        reportesFiltrarBtn = new javax.swing.JButton();
        reportesVistaPreviaBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        AperturaTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        cierreTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        reservasBtn = new javax.swing.JButton();
        mesasBtn = new javax.swing.JButton();
        cancelacionesBtn = new javax.swing.JButton();
        consultasBtn = new javax.swing.JButton();
        reportesBtn = new javax.swing.JButton();
        sucursalesBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Cliente");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setText("Fecha y Hora");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setText("Lugar");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        reservasLugarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventana", "Terraza", "General" }));

        jLabel5.setText("No. Personas");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        reservasCostoReservaTextField.setColumns(15);
        reservasCostoReservaTextField.setEditable(false);

        jLabel6.setText("Costo de reserva");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        reservasNumPersonasTextField.setColumns(15);

        reservasConfirmarBtn.setText("Confirmar");
        reservasConfirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasConfirmarBtnActionPerformed(evt);
            }
        });

        reservasConfirmarBtn1.setText("Calcular costo");
        reservasConfirmarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasConfirmarBtn1ActionPerformed(evt);
            }
        });

        reservasTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reservasTablaClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reservasConfirmarBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(reservasCostoReservaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reservasConfirmarBtn1))
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reservasLugarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(reservasNumPersonasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(reservasDateTimePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasDateTimePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservasLugarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservasNumPersonasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservasCostoReservaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservasConfirmarBtn1))
                .addGap(29, 29, 29)
                .addComponent(reservasConfirmarBtn)
                .addGap(18, 18, 18))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        mesasTablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Ubicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(mesasTablaMesas);

        jLabel8.setText("Mesas");

        jLabel9.setText("Tipo");

        jLabel10.setText("Ubicacion");

        mesasTipoMesaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeña", "Mediana", "Grande", " " }));

        mesasUbicacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terraza", "Ventana", "General" }));

        jLabel11.setText("Cantidad");

        mesasCantidadTxt.setColumns(10);
        mesasCantidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasCantidadTxtActionPerformed(evt);
            }
        });

        agregarMesasBtn.setText("Agregar Mesas");
        agregarMesasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMesasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel10)))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel11))
                            .addComponent(agregarMesasBtn)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mesasTipoMesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesasUbicacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesasCantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesasTipoMesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesasUbicacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesasCantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(agregarMesasBtn)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel3);

        cancelacionesTablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Codigo Mesa", "Fecha y hora", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(cancelacionesTablaReservas);

        cancelacionesMultaTxt.setColumns(10);
        cancelacionesMultaTxt.setEditable(false);

        cancelacionesCalcularMultaBtn.setText("Calcular Multa");
        cancelacionesCalcularMultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelacionesCalcularMultaBtnActionPerformed(evt);
            }
        });

        cancelacionesConfirmarBtn.setText("Confirmar");
        cancelacionesConfirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelacionesConfirmarBtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Reservas");

        cancelacionesTablaCancelaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Codigo Mesa", "Fecha", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(cancelacionesTablaCancelaciones);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cancelacionesCalcularMultaBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelacionesMultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelacionesConfirmarBtn)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelacionesMultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelacionesCalcularMultaBtn))
                .addGap(27, 27, 27)
                .addComponent(cancelacionesConfirmarBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel6);

        jLabel13.setText("Filtrar por rango de fechas");

        reportesTipoMesaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeña", "Mediana", "Grande", " " }));

        reportesUbicacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventana", "Terraza", "General", " " }));

        jLabel14.setText("Tipo de mesa");

        jLabel15.setText("Ubicacion");

        reportesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre ", "Fecha y hora", "Numero de personas", "Tipo de mesa", "Ubicacion", "Costo", "Cancelacion", "Multa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(reportesjTable);

        reportesFiltrarBtn.setText("Filtrar");
        reportesFiltrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesFiltrarBtnActionPerformed(evt);
            }
        });

        reportesVistaPreviaBtn.setText("Vista previa");
        reportesVistaPreviaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesVistaPreviaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reportesDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reportesTipoMesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reportesUbicacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reportesDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addComponent(reportesFiltrarBtn)
                            .addComponent(reportesVistaPreviaBtn))
                        .addGap(0, 340, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportesDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportesDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportesTipoMesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportesUbicacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(reportesFiltrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportesVistaPreviaBtn)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel7);

        jButton6.setText("anadir sucursal temporal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Hora de cierre");

        jLabel2.setText("Hora de apertura");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel12.setText("Sucursales");

        jButton8.setText("Editar Hora");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AperturaTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cierreTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jButton8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AperturaTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cierreTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("tab1", jPanel4);

        reservasBtn.setText("Reservas");
        reservasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasBtnActionPerformed(evt);
            }
        });

        mesasBtn.setText("Mesas");
        mesasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasBtnActionPerformed(evt);
            }
        });

        cancelacionesBtn.setText("Cancelaciones");
        cancelacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelacionesBtnActionPerformed(evt);
            }
        });

        consultasBtn.setText("Consultas");
        consultasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasBtnActionPerformed(evt);
            }
        });

        reportesBtn.setText("Reportes");
        reportesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesBtnActionPerformed(evt);
            }
        });

        sucursalesBtn.setText("Sucursales");
        sucursalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucursalesBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(reportesBtn)
                            .addComponent(consultasBtn)
                            .addComponent(cancelacionesBtn)
                            .addComponent(mesasBtn)
                            .addComponent(reservasBtn))
                        .addComponent(sucursalesBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelacionesBtn, consultasBtn, mesasBtn, reportesBtn, reservasBtn, sucursalesBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(reservasBtn)
                .addGap(18, 18, 18)
                .addComponent(mesasBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelacionesBtn)
                .addGap(18, 18, 18)
                .addComponent(consultasBtn)
                .addGap(18, 18, 18)
                .addComponent(reportesBtn)
                .addGap(18, 18, 18)
                .addComponent(sucursalesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservasConfirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasConfirmarBtnActionPerformed
      
        int selectedRow = reservasTablaClientes.getSelectedRow();
        System.out.println(reservasLugarComboBox.getSelectedItem().toString());
        long idMesa = mesaDAO.buscarMesaGeneral(Integer.parseInt(reservasNumPersonasTextField.getText()), reservasLugarComboBox.getSelectedItem().toString()).getId();
        long idCliente = clienteDAO.buscarClientePorTelefono(reservasTablaClientes.getValueAt(selectedRow, 1).toString()).getId();
        
        try {
            ReservaDTO reservaDTO = new ReservaDTO(
                    idCliente, 
                    idMesa, 
                    reservasDateTimePicker1.getDateTimePermissive(), 
                    Integer.parseInt(reservasNumPersonasTextField.getText()), 
                    Double.parseDouble(reservasCostoReservaTextField.getText()),
                    reservasLugarComboBox.getSelectedItem().toString());
            reservaDAO.registrarReserva(reservaDTO);
        } catch (Exception e) {
            System.out.println("error "+e);
        }
    }//GEN-LAST:event_reservasConfirmarBtnActionPerformed

    private void reservasConfirmarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasConfirmarBtn1ActionPerformed
        
        reservasCostoReservaTextField.setText(reservaBO.calcularCosto(Integer.parseInt(reservasNumPersonasTextField.getText())).toString());
    }//GEN-LAST:event_reservasConfirmarBtn1ActionPerformed

    private void reservasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasBtnActionPerformed
        jTabbedPane2.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel) reservasTablaClientes.getModel();
        clienteBO.limpiarTabla(model);
        clienteBO.cargarTablaClientes(model);
        
    }//GEN-LAST:event_reservasBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SucursalDTO sucursalDTO = new SucursalDTO("sucursalParis2", AperturaTimePicker.getTime(), cierreTimePicker.getTime());
        sucursalDAO.registrarSucursal(sucursalDTO);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void mesasCantidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesasCantidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesasCantidadTxtActionPerformed

    private void agregarMesasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMesasBtnActionPerformed
        
    }//GEN-LAST:event_agregarMesasBtnActionPerformed

    private void mesasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesasBtnActionPerformed
        jTabbedPane2.setSelectedIndex(1);
        DefaultTableModel model = (DefaultTableModel) mesasTablaMesas.getModel();
        mesaBO.limpiarTabla(model);
        mesaBO.cargarTablaMesa(model);
    }//GEN-LAST:event_mesasBtnActionPerformed

    private void reportesFiltrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesFiltrarBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) reportesjTable.getModel();
        reservaBO.limpiarTabla(model);
        reservaBO.cargarTablaReservas(model,
                reportesDatePicker1.getDate(),
                reportesDatePicker2.getDate(), 
                reportesTipoMesaComboBox.getSelectedItem().toString(), 
                reportesUbicacionComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_reportesFiltrarBtnActionPerformed

    private void cancelacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelacionesBtnActionPerformed
        jTabbedPane2.setSelectedIndex(2);
        DefaultTableModel model = (DefaultTableModel) cancelacionesTablaReservas.getModel();
        reservaBO.limpiarTabla(model);
        reservaBO.cargarTablaReservas(model);
        model = (DefaultTableModel) cancelacionesTablaCancelaciones.getModel();
        cancelacionesBO.limpiarTabla(model);
        cancelacionesBO.cargarTablaCancelaciones(model);
        
    }//GEN-LAST:event_cancelacionesBtnActionPerformed

    private void consultasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasBtnActionPerformed
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_consultasBtnActionPerformed

    private void reportesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesBtnActionPerformed
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_reportesBtnActionPerformed

    private void sucursalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalesBtnActionPerformed
        jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_sucursalesBtnActionPerformed

    private void reportesVistaPreviaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesVistaPreviaBtnActionPerformed
        jDialogReporte reporte = new jDialogReporte(this, rootPaneCheckingEnabled);
        DefaultTableModel model = (DefaultTableModel) reporte.reportejTable.getModel();
        reservaBO.limpiarTabla(model);
        reservaBO.cargarTablaReservas(model, reportesDatePicker1.getDate(),
                reportesDatePicker2.getDate(), 
                reportesTipoMesaComboBox.getSelectedItem().toString(), 
                reportesUbicacionComboBox.getSelectedItem().toString());
        reporte.nombreRestauranteJLabel.setText("Restaurante BDA");
        reporte.fechaJLabel.setText(LocalDate.now().toString());
        reporte.setVisible(rootPaneCheckingEnabled);
        
        
    }//GEN-LAST:event_reportesVistaPreviaBtnActionPerformed

    private void cancelacionesConfirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelacionesConfirmarBtnActionPerformed
        int selectedRow = cancelacionesTablaReservas.getSelectedRow();
        Reserva Reserva = reservaDAO.buscarReservaPorTelefono(cancelacionesTablaReservas.getValueAt(selectedRow, 1).toString());
        
        LocalDateTime fechaHora = (LocalDateTime) cancelacionesTablaReservas.getValueAt(selectedRow, 3);

        LocalDate fecha = fechaHora.toLocalDate();
        CancelacionDTO cancelacionDTO = new CancelacionDTO(
                fecha,
                Double.valueOf(cancelacionesMultaTxt.getText()),
                Reserva);
        cancelacionDAO.registrarCancelacion(cancelacionDTO);
        try {
            reservaDAO.cambiarEstadoReserva(Reserva.getId());
        } catch (Exception ex) {
            Logger.getLogger(frmRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) cancelacionesTablaReservas.getModel();
        reservaBO.limpiarTabla(model);
        reservaBO.cargarTablaReservas(model);
        model = (DefaultTableModel) cancelacionesTablaCancelaciones.getModel();
        cancelacionesBO.limpiarTabla(model);
        cancelacionesBO.cargarTablaCancelaciones(model);
        
    }//GEN-LAST:event_cancelacionesConfirmarBtnActionPerformed

    private void cancelacionesCalcularMultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelacionesCalcularMultaBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) cancelacionesTablaReservas.getModel();
        CancelacionesBO cancelacionesBO = new CancelacionesBO();
        LocalDateTime fechaHora = (LocalDateTime) cancelacionesTablaReservas.getValueAt
            (cancelacionesTablaReservas.getSelectedRow(), 3);
        double costoReserva = (Double) cancelacionesTablaReservas.getValueAt
            (cancelacionesTablaReservas.getSelectedRow(), 4);
        cancelacionesMultaTxt.setText(String.valueOf(cancelacionesBO.calcularMulta(fechaHora, costoReserva)));
        
    }//GEN-LAST:event_cancelacionesCalcularMultaBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            clienteBO.registrarClientes(clienteBO.generarClientes());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.TimePicker AperturaTimePicker;
    private javax.swing.JButton agregarMesasBtn;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JButton cancelacionesBtn;
    private javax.swing.JButton cancelacionesCalcularMultaBtn;
    private javax.swing.JButton cancelacionesConfirmarBtn;
    private javax.swing.JTextField cancelacionesMultaTxt;
    private javax.swing.JTable cancelacionesTablaCancelaciones;
    private javax.swing.JTable cancelacionesTablaReservas;
    private com.github.lgooddatepicker.components.TimePicker cierreTimePicker;
    private javax.swing.JButton consultasBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton mesasBtn;
    private javax.swing.JTextField mesasCantidadTxt;
    private javax.swing.JTable mesasTablaMesas;
    private javax.swing.JComboBox<String> mesasTipoMesaComboBox;
    private javax.swing.JComboBox<String> mesasUbicacionComboBox;
    private javax.swing.JButton reportesBtn;
    private com.github.lgooddatepicker.components.DatePicker reportesDatePicker1;
    private com.github.lgooddatepicker.components.DatePicker reportesDatePicker2;
    private javax.swing.JButton reportesFiltrarBtn;
    private javax.swing.JComboBox<String> reportesTipoMesaComboBox;
    private javax.swing.JComboBox<String> reportesUbicacionComboBox;
    private javax.swing.JButton reportesVistaPreviaBtn;
    private javax.swing.JTable reportesjTable;
    private javax.swing.JButton reservasBtn;
    private javax.swing.JButton reservasConfirmarBtn;
    private javax.swing.JButton reservasConfirmarBtn1;
    private javax.swing.JTextField reservasCostoReservaTextField;
    private com.github.lgooddatepicker.components.DateTimePicker reservasDateTimePicker1;
    private javax.swing.JComboBox<String> reservasLugarComboBox;
    private javax.swing.JTextField reservasNumPersonasTextField;
    private javax.swing.JTable reservasTablaClientes;
    private javax.swing.JButton sucursalesBtn;
    // End of variables declaration//GEN-END:variables
}
